### ISSUE TITLE
Sleep panic and video problems using AMD GPU

### ISSUE THREAD

**Issue by ants83** [vulgo/ga-h97n-wifi-hackintosh#19] opened 2022-03-29 08:44 UTC
After putting the machine into sleep mode it freezes and cannot be awaken. Hard reset is required to reboot. See attached panic log: 
[panic_sleep.log](https://github.com/vulgo/ga-h97n-wifi-hackintosh/files/8369217/panic_sleep.log)

My hardware configuration includes:

- GA-H97n-Wifi rev 1.0
- CPU Intel Core i7 5775c (Broadwell)
- Crucial Ballistix Tactical LP 2x8GB DIMM DDR3
- SAPPHIRE PULSE Radeon RX 560 2 GB GDDR5
- BroadCom BCM94360CS2 WIFI/Bluetooth Card through mini PCI-E adapter

Monitor is attached to AMD GPU, which works out of the box. Software config is the vanilla one from this repository, with recommended GPU settings for Broadwell in BIOS and config.plist.

**Comment by vulgo** [comment] 2022-03-29 10:45
Thanks. Please try these GPU settings in config.plist.

```
...
<key>DeviceProperties</key>
<dict>
    <key>Add</key>
    <dict>
        ...
        <key>PciRoot(0x0)/Pci(0x2,0x0)</key>
        <dict>
            ...
            <key>AAPL,ig-platform-id</key>
            <data>BAASBA==</data>
            <key>framebuffer-pipecount</key>
            <data>AAAAAA==</data>
            <key>framebuffer-portcount</key>
            <data>AAAAAA==</data>
            <key>framebuffer-memorycount</key>
            <data>AAAAAA==</data>
            <key>framebuffer-fbmem</key>
            <data>AAAAAA==</data>
            <key>framebuffer-flags</key>
            <data>AAAAAA==</data>
            ....
        </dict>
        ...
    </dict>
</dict>
```

I think those will make the Iris Pro work connectorless. The fault occured in Google Chrome renderer and I've never tested Broadwell with a discrete GPU, the iGPU seems like a good place to start.  Backup your EFI boot partition to e.g. USB in case this causes new problems.

**Comment by ants83** [comment] 2022-03-30 21:10
Thanks @vulgo. I replaced the iGPU configuration with the one you propose. Everything boots fine and the Iris Pro 6200 does not show up anymore in the Graphics/Display section in System Information. I'll test the configuration for some time and (hopefully not) report any further panic after sleep.

For completeness I need to report that for months I have been struggling with BIOS not retaining settings after a random number of reboots. Still after upgrading to rev F8 from F7, BIOS was always being reverted to the backup F7 image by the Dual BIOS feature. I had never tried to update to rev F9b (classified as beta) until today. After the update problems seem solved. Did you experience any problem in this regard?

**Comment by vulgo** [comment] 2022-03-30 22:28
@ants83 yes please provide further panic logs if you get them. It that's the case see if it panics without Chrome running and get that panic report also.

As well as panic reports `pmset -g log | grep -i failure` sometimes has useful information or just `pmset -g log`

There's instructions for getting a log from Chrome [here](https://support.google.com/chrome/a/answer/6271282).

I have rev 1.1 board, the dual bios is supposed to be automated but i have found it buggy and needed a special procedure, some dodgy power on and off timing trick to get things in a state where the dual BIOS would kick in. That said I've not experienced random loss of settings after reboots. Maybe NVRAM problem fixed it in F8? You had bad flash and/or buggy dual BIOS? The firmware on all these boards is pretty bad really.

**Comment by vulgo** [comment] 2022-03-30 22:46
I know when I first got this motherboard I contacted the previous owner to ask if it was working when he sold it to me cause i couldn't get it to do anything useful.

**Comment by ants83** [comment] 2022-03-31 20:26
Today another panic after sleep. See the attached log:

[panic_sleep_2.log](https://github.com/vulgo/ga-h97n-wifi-hackintosh/files/8392877/panic_sleep_2.log)

This is the output of `pmset`:


```bash
$ pmset -g log | grep -i failure
2022-03-29 08:53:25 +0200 Failure             	Failure during wake: SAT0(AppleAHCI) : Some drivers failed to handle setPowerState panic  	          
2022-03-30 08:46:29 +0200 Failure             	Failure during wake: PEG0(),IGPU(),B0D3(),SBUS() : Some drivers failed to handle setPowerState panic  	          
2022-03-30 21:51:11 +0200 Failure             	Failure during wake: PEG0() : Some drivers failed to handle setPowerState  	          
2022-03-31 02:49:15 +0200 Failure             	Failure during wake: PEG0(),IGPU(),B0D3(),SBUS() : Some drivers failed to handle setPowerState  	          
2022-03-31 08:43:42 +0200 Failure             	Failure during wake: PEG0() : Some drivers failed to handle setPowerState panic  	          
2022-03-31 22:17:11 +0200 Failure             	Failure during wake: PEG0(),IGPU(),B0D3(),SBUS() : Some drivers failed to handle setPowerState  
```

**Comment by vulgo** [comment] 2022-04-02 10:11
Backup EFI partition. Maybe try the iMac18,2 system definition (generate serials) and with the iGPU device properties from comment 2.  If you still get panics revert to iMac16,2 and please provide an IORegistry Explorer document.

**Comment by vulgo** [comment] 2022-04-21 18:04
@ants83 any updates re: kernel panics when waking from sleep?

**Comment by ants83** [comment] 2022-04-21 21:31
> @ants83 any updates re: kernel panics when waking from sleep?

@vulgo unfortunately I haven't been able to try your proposed solution. I will try a fresh installation of Macos 12 on another drive and use a fresh iMac18,2 system definition.

The PSU is a 350 Enermax Thriatlor Eco. By disabling automatic sleep, the system has been up and running for 15 days straight without any issue. Before this period I tried manual sleep and got a panic.

**Comment by vulgo** [comment] 2022-04-21 23:29
@ants83 i compiled the SSDT-SBUS-MCHC and added to config.plist, you will find on the master branch. Seeing as PCI devices seem to be disappearing and said drivers are supposed to control PCI power states it probably makes sense to have them loaded, not sure if you already did this.

Thanks for confirming PSU, re: firmware power management settings ErP and Platform Power Management can be disabled, i believe that is the default.

If you have time feel free to attach more complete logs (from boot to power state failure plus panic report) and if possible an IORegistry Explorer 2.1 document for each system definition logged.

**Comment by vulgo** [comment] 2022-04-22 12:32
@ants83 it might be useful to me to look at your current IORegistry in any case and see if i can update the intel graphics readme, it's not a priority.

**Comment by ants83** [comment] 2022-04-24 13:23
@vulgo which parts of the IORegistry are needed? Since in the IORegistry dump there are also sensible data (i.e. system serial number, user names) I would like to provide only necessary data for debug.

**Comment by vulgo** [comment] 2022-04-24 18:06
I do appreciate your concerns. Maybe i'm wrong but i don't think i uploaded a copy of my ioregistrys anywhere either. I'm interested in machine PM profile, power management logs, integrated logging logs, untested (by me) weg gpu device properties, AMD gpu, anything really. 2.1 registry explorer document would be convenient but its entirely up to you what you share and how, unless its with Apple in which case they probably know everything already. No joke.

**Comment by vulgo** [comment] 2022-04-24 18:17
I think with OpenCore on USB and macOS installed to a separate APFS volume skipping Apple ID creation you could probably clean things up somewhat, and take a look at OnionShare.

**Comment by ants83** [comment] 2022-04-24 19:38
> I think with OpenCore on USB and macOS installed to a separate APFS volume skipping Apple ID creation you could probably clean things up somewhat, and take a look at [OnionShare](https://github.com/onionshare/onionshare/releases).

This is what I'll do. I'll start with a new, disposable 16,2 iMac system definition and provide IORegistryExplorer 2.1 dump. After I'll use a 18,2 system definition and do the same.

**Comment by vulgo** [comment] 2022-04-24 20:00
Thank you @ants83 please do a quick

```
pmset -g log > $HOME/Desktop/pmlog.txt
```

after any panic.

Erase the log

```
sudo rm /var/log/powermanagement/*"
```

Thanks you again.

**Comment by ants83** [comment] 2022-04-30 22:50
I made a fresh macOS install on another drive. No luck with the iMac18,2 system definition. The system freezes (blank screen) as soon as I hit a keyboard button to awake the machine. Here are two `pmset` logs after two distinct freezes and hard reset.

[pmlog_imac18_2.txt](https://github.com/vulgo/ga-h97n-wifi-hackintosh/files/8597933/pmlog_imac18_2.txt)
[pmlog2_imac18_2.txt](https://github.com/vulgo/ga-h97n-wifi-hackintosh/files/8597934/pmlog2_imac18_2.txt)

You can find a IORegistryExplorer 2.1 dump here:

http://eomjgg4j6ew2didaf6u6562snvyy6etrq2f2eexvlszjspovaatiffid.onion

pk: YZID5KXEGC6F6A3FSEYCAGTLLAZDITLH55MATE35YDLCADLTW6MQ

The link will be deleted after the first download.

**Comment by vulgo** [comment] 2022-05-03 08:39
@ants83 thanks for the logs and link. The pmset logs show a similar fault to before. The onion link is down as of now, please can you re-upload - i was staying with friends for a few days and don't have tor access on my phone.

**Comment by ants83** [comment] 2022-05-03 21:01
@vulgo new link here (no key required):

http://maxgsmixvtxlu6ybpmlsur3efjuanwbo7xdpwhb2yv5ivraxjr5we7qd.onion

**Comment by vulgo** [comment] 2022-05-03 21:36
@ant83 thanks i have the IOReg. If you think its worth checking PCI devices are being properly standby powered in S5 maybe a live USB? Another hardware possibility is something on the bus e.g. wireless card. Anyway I'll take a look at the document and get back.

**Comment by ants83** [comment] 2022-05-03 21:44
I have a Broadcom BCM94360CS2 Airport Card installed in the mini PCI-Express slot through an adapter. It works out of the box.

I could try a Linux live USB distribution, if necessary.

**Comment by vulgo** [comment] 2022-05-03 22:16
@ants83 to be honest if it was a hardware problem i'd expect to see a difference in the power log. I will take some time to look at the document  but i saw `your loaded USBPorts.kext has 17 ports` as in one in the repo. Which is fine for booting and installing but is a possible cause for wake issues. Please refer to [README-usbtool.command.md](https://github.com/vulgo/ga-h97n-wifi-hackintosh/blob/main/README/README-usbtool.command.md).

Each USBPorts.kext is specific to the system definition. `usbtool.command` is supposed to be easy, you might need to right click and open depending on your security policy, but disabling any 2 or more ports should do, some possibilities

- SSP5 and SSP6 (same functionality you have now from boot)
- HS05 and HS06 (disables USB2 header)
- HS01, HS02, SSP1, SSP3 (disables USB3 header)

You can use [Hackintool](https://github.com/headkaze/Hackintool) if you prefer, the kext it generates should be compatible without `config.plist` edits at least.

**Comment by ants83** [comment] 2022-05-04 05:50
@vulgo sorry, I hadn't replaced the default USBPorts.kext with the one I typically use in my main volume installation, which has 15 ports. I'll replace the USBPorts.kext in the test volume, retry sleep and re-send logs/ioreg, still keeping iMac18,2 definition.

**Comment by vulgo** [comment] 2022-05-04 08:04
@vulgo for testing any merged port map can be quickly revealed with

```
echo $(ioreg -rc AppleUSBXHCILPTHB -k 'ports' | grep '"ports" = {"' | tr -d '[:space:]|/|')
```

**Comment by vulgo** [comment] 2022-05-04 20:55
@ants83 also please try with the WEG device properties for Broadwell in [README-Intel-Graphics.md](https://github.com/vulgo/ga-h97n-wifi-hackintosh/blob/main/README/README-Intel-Graphics.md#igpu-device-properties) and/or with the iGPU disabled in firmware settings. The WEG properties in comment 2 don't seem to be helping, i will look into it.

**Comment by ants83** [comment] 2022-05-04 21:09
@vulgo replaced USBPorts.kext with this one:

[USBPorts.kext.zip](https://github.com/vulgo/ga-h97n-wifi-hackintosh/files/8627188/USBPorts.kext.zip)

No luck:

[pmlog3_imac18_2.txt](https://github.com/vulgo/ga-h97n-wifi-hackintosh/files/8627190/pmlog3_imac18_2.txt)

Now I am switching to iMac16,2 sys def to make further trials.

**Comment by ants83** [comment] 2022-05-04 21:13
Meanwhile, during successive reboots and freezes, my BIOS is still randomly losing settings. When this happens, I have to restore recommended settings. My previous F9b ROM was also rewritten to stock F7 by DualBios.

**Comment by ants83** [comment] 2022-05-04 21:36
@vulgo With the iMac16,2 system definition, having disabled iGPU in BIOS and using these settings:

```
...
<key>DeviceProperties</key>
<dict>
    <key>Add</key>
    <dict>
        ...
        <key>PciRoot(0x0)/Pci(0x2,0x0)</key>
        <dict>
            <key>AAPL,ig-platform-id</key>
            <data>BAASBA==</data>
        </dict>
        ...
    </dict>
</dict>
...
```

I have been able to put into sleep and awake the machine a couple of times in a row.

See pmlog:

[pmlog_imac16_2_igpu_bios_off.txt](https://github.com/vulgo/ga-h97n-wifi-hackintosh/files/8627335/pmlog_imac16_2_igpu_bios_off.txt)

and ioreg dump:

http://it6e7q4yl2nlgp4znrpkpmyhycm6la5f6quijo3dc5dx5sq3jthfuoad.onion

**Comment by vulgo** [comment] 2022-05-04 22:35
@ants83 16,2 with iGPU disabled is probably a good bet. Some bits taken from the [WEG manual](https://github.com/acidanthera/WhateverGreen/tree/master/Manual) that may be of use

#### Force AMD AppleGVA decoder setting

```
defaults write com.apple.AppleGVA forceATI -boolean yes
```

#### Reset AppleGVA decoder setting

```
defaults delete com.apple.AppleGVA forceATI
```

#### Stop AppleVPA from trying to use iGPU, in `config.plist`

```
...
	<key>NVRAM</key>
	<dict>
		<key>Add</key>
		<dict>
			...
			<key>7C436110-AB2A-4BBB-A880-FE41995C9F82</key>
			<dict>
				...
				<key>boot-args</key>
				<string>keepsyms=1 shikigva=32 shiki-id=Mac-7BA5B2D9E42DDD94</string>
				...
			</dict>
		</dict>
        ...
    </dict>
...
```

Reset NVRAM from OpenCore after making changes to `config.plist` or changing system definition, please let me know how it goes over time. Hopefully the dual BIOS will settle again...

**Comment by ants83** [comment] 2022-05-05 05:35
@vulgo I left the machine sleeping all night. Unfortunately as soon as I hit a keyboard button to awake, the system restarted (not freezing).

[Uploading pmlog_imac16_2_igpu_bios_off_2.txt…]()

**Comment by vulgo** [comment] 2022-05-05 05:47
@ants83 from here it looks like the log attachment has failed, please confirm and edit the post, thanks,

**Comment by vulgo** [comment] 2022-05-05 06:43
Thank you @ants83, please attach `~/Desktop/powerd.log` zipped

```
log show -start '2022-05-05 00:46:31' -predicate 'process == "powerd"' -style compact > ~/Desktop/powerd.log
```

Output from `pmset -g`

Another ioregistry document if you have time. Thanks.

**Comment by ants83** [comment] 2022-05-06 07:20
Output from `pmset -g`:

```
System-wide power settings:
Currently in use:
 standby              1
 Sleep On Power Button 1
 womp                 1
 hibernatefile        /var/vm/sleepimage
 proximitywake        1
 powernap             0
 networkoversleep     0
 disksleep            10
 standbydelayhigh     86400
 sleep                0
 autopoweroffdelay    259200
 hibernatemode        0
 autopoweroff         1
 ttyskeepawake        1
 displaysleep         10
 highstandbythreshold 50
 standbydelaylow      86400
```
`~/Desktop/powerd.log` zipped:

[powerd.log.zip](https://github.com/vulgo/ga-h97n-wifi-hackintosh/files/8638273/powerd.log.zip)

**Comment by vulgo** [comment] 2022-05-06 20:59
@ants83 try with

```
sudo pmset -a proximitywake 0
```

the rest of the settings look agreeable.

I attach some [CPUFriend](https://github.com/acidanthera/CPUFriend) kexts, config.plist edits and .plist source.

Only make sure the order in `Kernel->Add` is `Lilu.kext` and `CPUFriendDataProvider.kext` before `CPUFriend.kext`

The changes are

```
      <key>ProximityWake</key>
      <integer>0</integer>
```

and

```
<key>DarkWakeServices</key>
    <dict>
        <key>DarkWakeBackgroundTasks</key>
        <integer>0</integer>
        <key>SleepServices</key>
        <integer>0</integer>
        ...
``` 
[cpu-friend.zip](https://github.com/vulgo/ga-h97n-wifi-hackintosh/files/8643586/cpu-friend.zip)

**Comment by vulgo** [comment] 2022-05-06 21:08
I keep seeing EHC1 and EHC2 in logs, i think with XHC set to enabled these should not be present in the device tree or ACPICA messages, unless it is a feature of the F7 BIOS.

**Comment by vulgo** [comment] 2022-05-07 05:48
@ants83 did you continue wit the 18,2 installation and just change the sysdef or is it a fresh installation?

**Comment by ants83** [comment] 2022-05-07 13:53
> @ants83 try with
> 
> ```
> sudo pmset -a proximitywake 0
> ```
> 
> the rest of the settings look agreeable.
> 
> I attach some [CPUFriend](https://github.com/acidanthera/CPUFriend) kexts, config.plist edits and .plist source.
> 
> Only make sure the order in `Kernel->Add` is `Lilu.kext` and `CPUFriendDataProvider.kext` before `CPUFriend.kext`
> 
> The changes are
> 
> ```
>       <key>ProximityWake</key>
>       <integer>0</integer>
> ```
> 
> and
> 
> ```
> <key>DarkWakeServices</key>
>     <dict>
>         <key>DarkWakeBackgroundTasks</key>
>         <integer>0</integer>
>         <key>SleepServices</key>
>         <integer>0</integer>
>         ...
> ```
> 
> [cpu-friend.zip](https://github.com/vulgo/ga-h97n-wifi-hackintosh/files/8643586/cpu-friend.zip)
> 
> You can reset pm override settings with
> 
> ```
> sudo rm /Library/Preferences/PowerManagement*.plist
> ```
> 
> Then use pmset or the settings app to match your previous ones.

@vulgo settings applied. Up to now it seems to work. I'll test for a longer period and report back.

[pmlog.txt](https://github.com/vulgo/ga-h97n-wifi-hackintosh/files/8645259/pmlog.txt)

**Comment by ants83** [comment] 2022-05-08 13:42
> @ants83 did you continue with the 18,2 installation and just change the sysdef or is it a fresh (or always 16,2) installation?

@vulgo I am using the same fresh installation used with sysdef 18,2 but with sysdef 16,2 now.

**Comment by ants83** [comment] 2022-05-09 20:13
@vulgo after two days of sleep and wakes without any problem, tonight the pc freezed after a couple of minutes after wake, as soon as I started playing a YouTube video.

**Comment by vulgo** [comment] 2022-05-10 03:35
@ants83 maybe `shikigva=40`

```
...
	<key>NVRAM</key>
	<dict>
		<key>Add</key>
		<dict>
			...
			<key>7C436110-AB2A-4BBB-A880-FE41995C9F82</key>
			<dict>
				...
				<key>boot-args</key>
				<string>keepsyms=1 shikigva=40 shiki-id=Mac-7BA5B2D9E42DDD94</string>
				...
			</dict>
		</dict>
        ...
    </dict>
...
```

**Comment by vulgo** [comment] 2022-05-10 04:58
If you keep having what sounds like GPU related issues please open another issue, try and provide a log

e.g. start some time before the freeze

```
log show -start 'YYYY-MM-DD HH:MM:SS' -style compact > ~/Desktop/freeze.log
```

e.g. or last 5 minutes

```
log show -last 5m -style compact > ~/Desktop/freeze.log
```

Edit with a text editor, delete from after the point where you have rebooted, delete messages a long time before the freeze,  or from before last sleep/wake if you think its relevant, zip it if it's a large file. Thanks.

**Comment by ants83** [comment] 2022-05-11 21:26
> The changes are
> 
> ```
>       <key>ProximityWake</key>
>       <integer>0</integer>
> ```
> 
> and
> 
> ```
> <key>DarkWakeServices</key>
>     <dict>
>         <key>DarkWakeBackgroundTasks</key>
>         <integer>0</integer>
>         <key>SleepServices</key>
>         <integer>0</integer>
>         ...
> ```
> 
> [cpu-friend.zip](https://github.com/vulgo/ga-h97n-wifi-hackintosh/files/8643586/cpu-friend.zip)
> 
> You can reset pm override settings with
> 
> ```
> sudo rm /Library/Preferences/PowerManagement*.plist
> ```
> 
> Then use pmset or the settings app to match your previous ones.

@vulgo unfortunately re-enabling iGPU in BIOS causes sleep/wake freezes. Anyway, perhaps I am missing something. I see that the above mentioned changes are included in the file `Mac-FFE5EF870D7BA81A.plist`. Do I need to manually replace the corresponding one in `X86PlatformPlugin.kext` or are the changes injected by `CPUFriend`?

**Comment by vulgo** [comment] 2022-05-11 21:48
Hello @ants83.

> unfortunately re-enabling iGPU in BIOS causes sleep/wake freezes

OK leave it disabled

> I see that the above mentioned changes are included in the attached Mac-FFE5EF870D7BA81A.plist

This is for source documentary purposes only, you can't replace the files in `X86PlatformPlugin.kext` as the file system is immutable

> are the changes injected by CPUFriend?

The entire `Mac-FFE5EF870D7BA81A.plist` with changes are injected by `CPUFriendDataProvider.kext` and `X86PlatformPlugin.kext` is patched by `CPUFriend.kext`. Please ignore the `CPUFriendDataProvider.kext` in `16,2-Default` directory, that shouldn't be there. The kexts you want are in `EFI/OC/Kexts`

From CPUFriend instructions:

> ### Usage of ResourceConverter.sh
> 
> --kext /path/to/file Create CPUFriendDataProvider.kext with information provided by file.
> 
> --acpi /path/to/file Create ssdt_data.dsl with information provided by file.

We don't use `--acpi` method as it conflicts with `SSDT-PLUG`, `--kext` argument takes a complete property list such as `Mac-FFE5EF870D7BA81A.plist` in the `16,2-custom` directory and generates the codeless `CPUFriendDataProvider.kext`

**Comment by ants83** [comment] 2022-05-12 20:53
> @vulgo after two days of sleep and wakes without any problem, tonight the pc freezed after a couple of minutes after wake, as soon as I started playing a YouTube video.

@vulgo same behavior experienced again. It seems the freezes are still related to power management:

[pmlog.txt](https://github.com/vulgo/ga-h97n-wifi-hackintosh/files/8682528/pmlog.txt)


[panic.log](https://github.com/vulgo/ga-h97n-wifi-hackintosh/files/8682530/panic.log)

**Comment by vulgo** [comment] 2022-05-12 22:20
@ant83 please send ioregistry document and logs as in this comment [issuecomment-1121932661](https://github.com/vulgo/ga-h97n-wifi-hackintosh/issues/19#issuecomment-1121932661). Also please confirm XHC is set to enabled in firmware settings.

**Comment by ants83** [comment] 2022-05-13 07:26
@vulgo ioregistry and freeze log around the minute 2022-05-12 22:37:43:

http://t2n764wfmehkpwssjvi3ppwe5cpknci72jlttaucdef3nx7ljgasimyd.onion

**Comment by vulgo** [comment] 2022-05-13 08:06
If you disable the iGPU in BIOS you probably require the [shiki WEG boot arguments](https://github.com/vulgo/ga-h97n-wifi-hackintosh/issues/19#issuecomment-1121849401) otherwise apps will try decoding the with IGPU. This may be the cause of the IMEI wake failure.

When I said enable the iGPU as an alternative I meant these as part of the enable/disable process.

### More Information

- [FAQ.Shiki.en.md](https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.Shiki.en.md/)
- [Dortania Boot Flags](https://dortania.github.io/GPU-Buyers-Guide/misc/bootflag.html)

**Comment by vulgo** [comment] 2022-05-13 09:20
@ants83 i think you have two options:

- disable iGPU in firmware settings and use WEG to patch around the SMBIOS (shiki arguments)
- ask [headkaze](https://github.com/headkaze/Hackintool) about patching the desktop Broadwell framebuffer for connector-less operation

**Comment by ants83** [comment] 2022-05-14 10:15
> If you disable the iGPU in BIOS you probably require the [shiki WEG boot arguments](https://github.com/vulgo/ga-h97n-wifi-hackintosh/issues/19#issuecomment-1121849401) otherwise apps will try decoding the with IGPU. This may be the cause of the IMEI wake failure.

@vulgo I see that in the WEG boot arguments now you have `shiki-id=Mac-7BA5B2D9E42DDD94`, which corresponds to a iMacPro1,1 SMBIOS. Do I need to also generate a corresponding serial?

**Comment by vulgo** [comment] 2022-05-14 10:17
@ants boot arguments from your most recent IOReg

```
keepsyms=1 swd_panic=1
```

**Comment by ants83** [comment] 2022-05-14 10:19
> @ants boot arguments from your most recent IOReg
> 
> ```
> keepsyms=1 swd_panic=1
> ```

Yes, I had removed WEG boot arguments after a freeze. Now I am reading them.

**Comment by vulgo** [comment] 2022-05-14 10:22
As I edited above in case you miss it, no corresponding serial required, WEG just patches the AppleGVA and AppleVPA processes.

If the iGPU is disabled the WEG arguments are needed e.g. for watching youtube videos. `forceATI=yes` defaults preference may or may not be required with `shiki-id=Mac-7BA5B2D9E42DDD94` I don't know

**Comment by ants83** [comment] 2022-05-15 20:04
@vulgo no luck. As usual, after a certain amount of successful sleep/wake cycles, the machine got stuck at the last one. However, this one did not result in a freeze but in a dark screen appearing every couple of seconds, and the mouse pointer showing up.

[pmlog.txt](https://github.com/vulgo/ga-h97n-wifi-hackintosh/files/8695883/pmlog.txt)

The `forceATI=yes` defaults preference was not set. I'll try with it set now.

**Comment by vulgo** [comment] 2022-05-15 21:31
Sorry i cannot discern clearly what you were doing or the system
configuration from the pmlog.txt - when you say freeze you mean on wake or
on playing videos. Need to see ioreg of system before freeze and after any
configuration changes. If using chrome at point of freeze need to see
chrome log.

**Comment by vulgo** [comment] 2022-10-09 00:50
I'm closing this, please feel free to reopen it if you are able to provide further details.

**Closed** 2022-10-09 00:51 UTC
Labels: intel-gpu, power-management, broadwell

**Comment by vulgo** [comment] 2022-10-11 08:47
I do appreciate your concerns. Maybe i'm wrong but i don't think i uploaded
a copy of my ioregistrys anywhere either. I'm interested in machine PM
profile, power management logs, integrated logging logs, untested (by me)
weg gpu device properties, AMD gpu, anything really. 2.1 registry explorer
document would be convenient but its entirely up to you what you share and
how, unless its with Apple in which case they probably know everything
already. No joke.
